#version: "3.9"
services:
  graphql-router:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: ./node_modules/.bin/nodemon graphql-router.js
    ports:
      - "6100:6100"
    volumes:
      - .:/app/
    restart: always
    environment:
      - DOCKER_TAG=${DOCKER_TAG-latest}
      - ENV_ID=dev
#    network_mode: bridge
#    networks:
#      - gratheon
#networks:
#  gratheon:

