version: '3.8'
services:
  graphql-router:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "6100:6100"
    environment:
      - DOCKER_TAG=${DOCKER_TAG-latest}
      - ENV_ID=prod
    restart: always
    network_mode: host