version: '3.8'
services:
  graphql-router:
    build: .
    command:
      node /app/graphql-router.js
    ports:
      - "6100:6100"
    # volumes:
    #   - .:/app/
    restart: always
    environment:
      - DOCKER_TAG=${DOCKER_TAG-latest}
      - ENV_ID=prod
    network_mode: host