server {
    server_name  graphql.gratheon.com;

    client_body_buffer_size 30m;
    client_max_body_size 30m;

    client_header_buffer_size 4k;
    large_client_header_buffers 4 32k;

    gzip on;
    gzip_types    text/plain application/javascript application/x-javascript text/javascript text/xml text/css application/json application/graphql-response+json;

    root /www/graphql-router;
    index index.html;

    location / {
    	proxy_set_header X-Real-IP $remote_addr;
		proxy_pass http://127.0.0.1:6100;
    }


    listen 443 ssl;
    ssl_certificate /etc/letsencrypt/live/graphql.gratheon.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/graphql.gratheon.com/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
}
server {
    server_name  graphql.gratheon.com;
    listen 80;
    return 404;
}
server {
    if ($host = graphql.gratheon.com) {
        return 301 https://$host$request_uri;
    }


    server_name  graphql.gratheon.com;
    listen 80;
    return 404;
}
